version: 1
services:
  web:
    type: web
    buildCommand: "python manage.py collectstatic --noinput"
    runCommand: "gunicorn config.wsgi --log-file -"
    env:
      DJANGO_SETTINGS_MODULE: "Porfolio.core.settings"
    healthCheck:
      path: "/"
      interval: 10s
      timeout: 2s
      healthyThreshold: 2
      unhealthyThreshold: 3
